### PR TITLE
Create foo.txt

### PR DESCRIPTION
**Pull request by mario-kr**
ddöfgkjasdölkgfjasdfkögöjlkädgf

### CODE REVIEW

**Comment by mario-kr** [comment]
you might also want to check for the keywork `amend!`

**Comment by matthiasbeyer** [comment]
Yeah, the action does not support this AFAIK.

**Comment by matthiasbeyer** [comment]
Care to rebase this?

**Comment by mario-kr** [comment]
rebased + force pushed

**Comment by matthiasbeyer** [comment]
workflow approved.

**Comment by matthiasbeyer** [comment]
For fucks sake, github I HATE you.

**Comment by matthiasbeyer** [comment]
Please rebase once more... :cry:

**Comment by mario-kr** [comment]
done

**Comment by matthiasbeyer** [comment]
`Resource not accessible by integration`

As expected. Thanks for your time!

**Pull request closed without merging**
